ext3: fix build error when subtree id is disabled
When we disable subtree id we will get the following error messages:
fs/statfs.c: In function ‘vfs_statfs’:
fs/statfs.c:131: error: unused variable ‘subtree’
fs/statfs.c:130: error: unused variable ‘error1’
make[1]: *** [fs/statfs.o] Error 1

This commit tries to fix this problem.  From the messages we can see all
error are 'unused' issues.  So only we need to do is not to build these
symbols without subtree id.

Patch-mainline: in house
Reference: 
Signed-off-by: Zheng Liu <wenqing.lz@taobao.com>